### ISSUE TITLE
Configurable Balance type

### ISSUE THREAD

**Issue by enthusiastmartin** [galacticcouncil/HydraDX-math#13]
Currently, within this crate Balance type is set to u128. 

It would be interesting to support any type. This requires major refactor, think about design etc. So it is one for the future.

**Comment by jak-pan** [comment]
Do you think that we could make a crate with HydraDX-primitives? We have some of the primitives tied to substrate though.

**Comment by enthusiastmartin** [comment]
I would like to not depend on substrate- as even simple dependency usually pulls in other substrate stuff. 

But what i have in mind for this is quite generic approach, so then you could plug in whatever you want.

**Comment by enthusiastmartin** [comment]
not really needed and it would require lot of effort.
