### ISSUE TITLE
Change sell and buy to in and out.

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-math#5]
companion to  https://github.com/galacticcouncil/HydraDX-node/issues/111

**Comment by RoboRambo** [comment]
If I understand correctly, then:

**1. rename calculate_buy_price**
Suggestion:
calculate_price_in

**2. rename calculate_sell_price**
Suggestion:
calculate_price_out

**Comment by jak-pan** [comment]
If we are going to change them it should definitely be like this

```
calculate_buy_price(buy_reserve, sell_reserve, buy_amount): sell_amount
->
calculate_in_given_out(out_reserve, in_reserve, amount_out): amount_in
```

```
calculate_sell_price(sell_reserve, buy_reserve, sell_amount): buy_amount
->
calculate_out_given_in(in_reserve, out_reserve, amount_in): amount_out
```

to be clear since this issue is about being more clear.

**Comment by RoboRambo** [comment]
Is the order of the arguments correct?
Isnt in_reserve the replacement for buy_reserve?

**Comment by jak-pan** [comment]
> Is the order of the arguments correct?
> Isnt in_reserve the replacement for buy_reserve?

in_reserve is reserve of asset to be sold = asset going -> in to the pool. 
buy_reserve is reserve of the asset that is bought from the pool -> out_reserve

we're changing the point of view here from the user to the pool.
