### ISSUE TITLE
[Audit_RV] Inconsistent sign for 0 in BalanceUpdate

### ISSUE THREAD

**Issue by yanliu18** [galacticcouncil/HydraDX-math#52]
The following code could result in `Increase(0)` which could cause false failure in balance updates, for example, the hub asset liquidity update in Line 993 of [PR445](https://github.com/galacticcouncil/HydraDX-node/pull/445/commits/af60845a7f40caa6183d6bb203b9ce22f5384970#diff-afe70d3b919a05f12410e43dfc5d5808df412035c6d4f1ec0bda78277dd41412R993).
https://github.com/galacticcouncil/HydraDX-math/blob/f4dab244bb5d57971325f0ba6fbb8f6c1353beeb/src/omnipool/types.rs#L74

https://github.com/galacticcouncil/HydraDX-math/blob/f4dab244bb5d57971325f0ba6fbb8f6c1353beeb/src/omnipool/types.rs#L98

https://github.com/galacticcouncil/HydraDX-math/blob/f4dab244bb5d57971325f0ba6fbb8f6c1353beeb/src/omnipool/types.rs#L116

**Comment by enthusiastmartin** [comment]
Added special of increase(0) to avoid false failures.

**Comment by enthusiastmartin** [comment]
fixed #61
