### ISSUE TITLE
[Audit_RV] Consistency: ImbalanceLRNA.negative is not a precondition in most, but not all exchange types.

### ISSUE THREAD

**Issue by virgil-serbanuta** [galacticcouncil/HydraDX-math#67]
All endpoints involving liquidity check HubAssetImbalance.negative both as a precondition and as a postcondition. However, when doing exchanges it is checked only as a postcondition, the only exception being when selling LRNA:

https://github.com/galacticcouncil/HydraDX-math/blob/b459299bb4245514782d741faf028bb971a6f756/src/omnipool/math.rs#L127-L129

Most likely this has no user-visible effects, it’s just that the ImbalanceLRNA.negative invariant is checked in a non-consistent way.

**Comment by enthusiastmartin** [comment]
fixed in #70
